### ISSUE TITLE
Duplicate Words in User Input

### ISSUE THREAD

**Issue by rcallen89** [iEv0lv3/algorithm_sort#2]
Currently checks the user input for duplicate words against the original array (lower case and capitalized are considered the same word), but the user input doesn't check itself for duplicate words.  This allows multiples of a single word into the array.

**Comment by iEv0lv3** [comment]
Issue solved through `method_integration` branch merge. When `the_sort` method is called, it contains logic which will check for and remove duplicates from the sorting process.
